### ISSUE TITLE
Check if the utility token contracts are identical in all repository

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/utilitytoken-contracts#1]
Check if the following contracts are identical in all repository.
- UtilityToken.sol
- UtilityTokenInterface.sol
- UtilityTokenRequiredInterface.sol

If it is not identical then 
- Find the differences.
- Discuss with the team.
- After discussion create the followup tickets

**Comment by schemar** [comment]
Removed EIP20 Token as that is currently not in the scope of this issue (ref. https://github.com/OpenST/brandedtoken-contracts/issues/166#issuecomment-484121171 and https://github.com/OpenST/mosaic-contracts/issues/712#issuecomment-484109470)

**Comment by sarvesh-ost** [comment]
**1. Observations about _UtilityToken.sol_** 


| Topic                                              	| mosaic-contracts                                                          	| brandedtoken-contracts                                                    	|
|----------------------------------------------------	|---------------------------------------------------------------------------	|---------------------------------------------------------------------------	|
| Position of organization contract                  	| import "../lib/OrganizationInterface.sol"; import "../lib/Organized.sol"; 	| import "./OrganizationInterface.sol"; import "./Organized.sol";           	|
| increaseSupplyInternal argument _account is payable 	| function increaseSupplyInternal(address _account,uint256 _amount)         	| function increaseSupplyInternal(address payable _account,uint256 _amount) 	|

_Note:_ There are some differences in the comments but they are minor.
**2. Observation about UtilityTokenInterface.sol**
1. Only minor documentation differences.

**3. Observation about UtilityTokenRequiredInterface.sol.**
This interface only exists in openst-contracts repository.

**Comment by schemar** [comment]
OK sounds nice. However, in the first line of your table you reference organization contracts, whereas this ticket should address utility token contracts 🤔

**Comment by sarvesh-ost** [comment]
> OK sounds nice. However, in the first line of your table you reference organization contracts, whereas this ticket should address utility token contracts 🤔

The first line is about imports in utility contract.  Both repositories have different import location.

**Comment by schemar** [comment]
I don't get it 😳 It says "Position of *organization* contract" and lists organization contract locations. Isn't this about utility token contracts? 🐨

**Comment by sarvesh-ost** [comment]
Yes, Sorry for misleading words. Updated `Position of organization contract` -> `Differences in import statement`

**Comment by schemar** [comment]
Ah ok I get it, sorry 😅 In that case that isn't a problem when it gets unified 🎉

**Comment by schemar** [comment]
Did you find out *why* the `_account` is `payable` in brandedtoken, but not `payable` in mosaic-contracts? 🤔

**Comment by sarvesh-ost** [comment]
I think, `payable` is not needed in `increaseSupplyInternal ` in `branded-token-contract` repository.  It seems like a dead code. Payable is added for ost prime. if you see below implementation, base token transfer happens after `increaseSupplyInternal` call. So `_account` in `increaseSupplyInternal` doesn't need to be payable. 

```
    function increaseSupply(
        address payable _account,
        uint256 _amount
    )
        external
        onlyInitialized
        onlyCoGateway
        mutex
        returns (bool success_)
    {
        success_ = increaseSupplyInternal(address(this), _amount);
        _account.transfer(_amount);
    }
```
In nut shell, brandedtoken-contracts `increaseSupplyInternal seems to be outdated

**Comment by schemar** [comment]
I think your work is done here @sarvesh-ost ? I don't know where to document that your findings must be taken into consideration in the utility token contracts repository.

Please re-open if anything unclear or still required.

**Comment by gulshanvasnani** [comment]
There is one more difference :
UtilityToken contract in mosaic-contracts doesn't have method `setCoGatewayInternal`.
In UBT, `setCogateway` method calls `setCogatewayInternal` method of UtilityToken.
