### ISSUE TITLE
Use git-submodules to include organization contracts

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/utilitytoken-contracts#3]
- Use `git-submodules` to include these contracts.
- Add the submodule inside `contracts` so that it is directly available to Truffle.

**Comment by schemar** [comment]
See also the discussion here on git submodules vs. npm dependencies: https://github.com/OpenST/developer-guidelines/issues/20#issuecomment-483185693

**Comment by sarvesh-ost** [comment]
Plan to work on this ticket, can't assign me due to lack of access.
