### ISSUE TITLE
Script to auto-generate contract interacts files

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/utilitytoken-contracts#5]
This issue is blocked by #2 

Contract interacts creation in type-script has a lot of boilerplate code and its time consuming to maintain it manually. It will be helpful to consume APIs with proper typed parameters.

- Use `@0xproject/abi-gen` to generate contract interacts 
(If you have a suggestion for the libraries that can be used, please suggest)
- Add  NPM command to run the script e.g: `npm run generate`

**Comment by schemar** [comment]
> Contract interacts creation in type-script has a lot of boilerplate code and its time consuming to maintain it manually. It will be helpful to consume APIs with proper typed parameters.

Can you be more specific please? What kind of boilerplate? How does it need to be maintained manually?

**Comment by schemar** [comment]
Doing it *manually* is time consuming ...
